service: message-board

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  environment:
    DYNAMODB_TABLE: Messages
  logs:
    restApi:
      accessLogging: true
      executionLogging: true
      fullExecutionData: true
      level: INFO
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:GetItem
            - dynamodb:Query
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}
            - arn:aws:logs:${self:provider.region}:*:log-group:/aws/lambda/*

frameworkVersion: '^4.4.0'
build:
  esbuild: false

plugins:
  - serverless-plugin-include-dependencies

package:
  individually: true
  exclude:
    - '**/*'
  include:
    - handler.js
    - node_modules/@aws-sdk/client-dynamodb/** 
    - node_modules/uuid/** 

functions:
  createMessage:
    handler: handler.createMessage
    events:
      - http:
          path: messages
          method: post
          cors: true

  getMessages:
    handler: handler.getMessages
    events:
      - http:
          path: messages
          method: get
          cors: true

  updateMessage:
    handler: handler.updateMessage
    events:
      - http:
          path: messages/{id}
          method: put
          cors: true

resources:
  Resources:
    MessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1